version: '3'

services:
  mongo1-rep:
        ports:
            - '27017:27017'
        restart: always
        logging:
            options:  
                max-size: 1g
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        #     - MONGO_INITDB_ROOT_PASSWORD=bdung
        image: mongo
  mongo2-rep:
        ports:
            - '27018:27017'
        restart: always
        logging:
            options:
                max-size: 1g
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        #     - MONGO_INITDB_ROOT_PASSWORD=bdung
        image: mongo      
  rabbit:
        ports:
            - '1567:567'
        restart: always
        image: rabbitmq:3.10.7-management   

  worker1:
    build:
      context: worker
      dockerfile: Dockerfile
    ports:
      - "8082:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - manager

  worker2:
    build:
      context: worker
      dockerfile: Dockerfile
    ports:
      - "8083:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - manager

  manager:
    build:
      context: manager
      dockerfile: Dockerfile
    ports:
      - "8085:8080"