version: '3'

services:
  manager:
    build:
      context: manager
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - crackhash

  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - manager
    networks:
      - crackhash

networks:
  crackhash:
    driver: bridge